//"use client";
//prerequisites and type imports
import React, { ReactNode } from 'react'

import type { Session } from "next-auth"

//predefined layout and provider files
import Providers from './provider';
import BaseLayout from '../components/BaseLayout';
import Sidebar from '../components/Sidebar';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      { /**className={inter.className}* */}
      <body className='bg-yellow--300 h-full w-full'
        
        
        >
        
        <Providers >

   <BaseLayout> {children}</BaseLayout>
       
      
       
            </Providers>
      </body>
    </html>
  )
}



  /*function Auth({ children }:any) {
    // if `{ required: true }` is supplied, `status` can only be "loading" or "authenticated"
    const { status } = useSession({ required: true,
      onUnauthenticated() {
          //not
      },
     })
  
    if (status === "loading") {
      return <div>Loading...</div>
    }
  
    return children
  }*/