//importing out utilities from redux toolkiits
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'


//this was autogenerated using our rapidapi extension with our api request(url, headers) and the code button 
//we dont actually need this code, its just easy to have it here so we can copy our api links and headers

export const shazamCoreApi = createApi({
    //name of api, reducer path
    reducerPath: 'shazamCoreApi',
    //we also need a function call for baseQuery
    baseQuery: fetchBaseQuery({
        baseUrl: 'https://shazam-core.p.rapidapi.com/v1',
        //endpoints woill be added to our base query to get the charts etc
        prepareHeaders: (headers) => {
            headers.set('X-RapidAPI-Key', '4dbc6fc3e0mshf8d6ef2f69cd271p16f0f3jsn3ca073a064c0');
            headers.set('X-RapidAPI-Host', 'shazam-core.p.rapidapi.com');
            //we will move our headers to environment variabkles
            return headers;
        }
        //autonatic call back function
    }),
    //now we declare our endpiunts that  require a builder prop
    endpoints: (builder) => ({
        //this is called as a hook in redu toolkiot
        getTopCharts: builder.query({
            //query is an arrow function that return s a string
            query: () => '/charts/world'
        }),
        //write our other queries here
    }),

});
export const {
    //always write use infront of your endpoint names
    useGetTopChartsQuery,
} = shazamCoreApi;